
#spring:
#  servlet:
#    multipart:
#      max-file-size: 200MB
#      max-request-size: 200MB
#
#  # 日期返回格式
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        min-idle: 0
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#    connect-timeout: 30000ms

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/ftm-system?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
#    username: root
#    password: root

#  data:
#    mongodb:
#      host: 192.168.200.125
#      port: 25002
#      database: DataCenter
  #      authentication-database: admin
  #      username: root
  #      password: Ry@Mysq.2021


#
#mybatis-plus:
#  mapper-scan-package: top.anets.modules
#  type-aliases-package: top.anets.modules.**.entity
#  # xxxMapper.xml 路径
#  mapper-locations: classpath*:top/anets/modules/**/mapper/**/*.xml





