server:
  port: 8082
spring: # 注意追加在配置文件中已经有 spring 前缀的后面
  application:
    name: ftm-file
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  base-package: top.anets.file

#  cloud:
#  nacos:
#    discovery:
#      server-addr: localhost:8848 # 服务注册中心地址

  #数据库连接信息
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/ftm-file?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
mybatis:
  table:
    auto: update
    #create系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
    #update系统会自动判断哪些表是新建的．哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。#none系统不做任何处理。
    #add新增表/新增字段/新增索引新增唯一约束的功能，不做做修改和删除(只在版本1.0.9.RELEASE及以上支持)。model:
  model:
    pack: top.anets.file.**.entity #扫描用于创建表的对象的包名，多个包用"."隔开
  database:
    type: mysql #数据库类型目前只支持mysql
mybatis-plus:
  mapper-scan-package: top.anets.file.dao
  type-aliases-package: top.anets.file.**.entity
  # xxxMapper.xml 路径
  mapper-locations: classpath*:top/anets/modules/**/mapper/**/*.xml