server:
  port: 8082
spring: # 注意追加在配置文件中已经有 spring 前缀的后面
  application:
    name: ftm-file
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  base-package: top.anets.file
  resources:
    static-locations: classpath:/static/dist/
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  #  cloud:
#  nacos:
#    discovery:
#      server-addr: localhost:8848 # 服务注册中心地址

  #数据库连接信息
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/ftm-file?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL

mybatis-plus:
  mapper-scan-package: top.anets.file.dao
  type-aliases-package: top.anets.file.**.entity
  # xxxMapper.xml 路径
  mapper-locations: classpath*:top/anets/modules/**/mapper/**/*.xml


file:
  oss:
    enable: true
    endpoint: http://192.168.10.11:9006 # 对象存储服务的URL
    bucketName: oss # 因为url本身代表了存储桶，这里空着不用配置
    accessKey: root # 账户ak
    secretKey: IjudisjIUJId498eNINxx # 账户sk