  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 服务注册中心地址
    sentinel:  ## 流控
      log:
        dir: /logs
        switch-pid: true
      transport:
        # sentinel dashboard的地址(sentinel的地址--8080监控当前8500微服务)
        dashboard: localhost:8080
        clientIp: 127.0.0.1
        # 为应用开启额外的端口，上报监控信息
        # 默认为8719端口，加入被占用将会自动从8719开始+1扫描，直至找到未被占用的端口地址
        port: 8725
      datasource:
        flow: #流控规则
          nacos:
#            namespace: 这个很害人 ，必须填写id才行，要么不填,否则，nacos更新后内存无法更新规则
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: flow
#            username: nacos #高版本的nacos中，不管是进行discover还是config配置都是需要配置username和password的
#            password: nacos
        degrade: #熔断规则
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: degrade
#            username: nacos
#            password: nacos
        system: #系统规则
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: system
#            username: nacos
#            password: nacos
        authority: #授权规则
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: authority
#            username: nacos
#            password: nacos
        param-flow: #热点参数规则
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: param-flow
#            username: nacos
#            password: nacos